- name: create log directory
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify: test and reload nginx
  tags:
    - nginx_server-setup

- name: install nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: yes
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0640
  notify: test and reload nginx
  tags:
   - nginx_install-configuration

- name: install nginx server security file
  template:
    src: security.conf.j2
    dest: /etc/nginx/security.conf
    force: yes
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0640
  notify: test and reload nginx
  tags:
   - nginx_install-configuration

- name: enable and start nginx service
  service:
    name: nginx
    enabled: yes
  notify: restart nginx
  tags:
    - nginx_service-setup
