---
- name: test and reload nginx
  command: nginx -t
  notify:
    - reload nginx

- name: test and restart nginx
  command: nginx -t
  notify:
    - restart nginx

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted
